<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TsvConsult\Module'                        => __DIR__ . '/Module.php',
    'TsvConsult\Controller\TsvConsultController' => __DIR__ . '/src/TsvConsult/Controller/TsvConsultController.php',
    'TsvConsultTest\Framework\TestCase'        => __DIR__ . '/tests/TsvConsult/Framework/TestCase.php',
    'TsvConsultTest\SampleTest'                => __DIR__ . '/tests/TsvConsult/SampleTest.php',
);
